<?php

// autoload_psr4.php @generated by Composer

$vendorDir = dirname(dirname(__FILE__));
$baseDir = dirname($vendorDir);

return array(
    'ZN\\XML\\' => array($vendorDir . '/package-xml'),
    'ZN\\Validation\\' => array($vendorDir . '/package-validation'),
    'ZN\\Storage\\' => array($vendorDir . '/package-storage'),
    'ZN\\Shopping\\' => array($vendorDir . '/package-shopping'),
    'ZN\\Services\\' => array($vendorDir . '/package-services'),
    'ZN\\Security\\' => array($vendorDir . '/package-security'),
    'ZN\\Response\\' => array($vendorDir . '/package-response'),
    'ZN\\Request\\' => array($vendorDir . '/package-request'),
    'ZN\\Remote\\' => array($vendorDir . '/package-remote'),
    'ZN\\Protection\\' => array($vendorDir . '/package-protection'),
    'ZN\\Prompt\\' => array($vendorDir . '/package-prompt'),
    'ZN\\Pagination\\' => array($vendorDir . '/package-pagination'),
    'ZN\\Language\\' => array($vendorDir . '/package-language'),
    'ZN\\Image\\' => array($vendorDir . '/package-image'),
    'ZN\\Hypertext\\' => array($vendorDir . '/package-hypertext'),
    'ZN\\Helpers\\' => array($vendorDir . '/package-helpers'),
    'ZN\\Generator\\' => array($vendorDir . '/package-generator'),
    'ZN\\Filesystem\\' => array($vendorDir . '/package-filesystem'),
    'ZN\\EventHandler\\' => array($vendorDir . '/package-event-handler'),
    'ZN\\Email\\' => array($vendorDir . '/package-email'),
    'ZN\\DateTime\\' => array($vendorDir . '/package-datetime'),
    'ZN\\Database\\' => array($vendorDir . '/package-database'),
    'ZN\\DataTypes\\' => array($vendorDir . '/package-datatypes'),
    'ZN\\Cryptography\\' => array($vendorDir . '/package-cryptography'),
    'ZN\\Crontab\\' => array($vendorDir . '/package-crontab'),
    'ZN\\Console\\' => array($vendorDir . '/package-console'),
    'ZN\\Compression\\' => array($vendorDir . '/package-compression'),
    'ZN\\Comparison\\' => array($vendorDir . '/package-comparison'),
    'ZN\\Captcha\\' => array($vendorDir . '/package-captcha'),
    'ZN\\Cache\\' => array($vendorDir . '/package-cache'),
    'ZN\\Buffering\\' => array($vendorDir . '/package-buffering'),
    'ZN\\Authorization\\' => array($vendorDir . '/package-authorization'),
    'ZN\\Authentication\\' => array($vendorDir . '/package-authentication'),
    'ZN\\' => array($vendorDir . '/package-zerocore'),
);
